version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "12181:2181"                                                                    # change, corresponds to: kafka->environment->KAFKA_ZOOKEEPER_CONNECT->...:?2181
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_SERVER_ID: 1                                                            # change
      ZOOKEEPER_SERVERS: "${NODE_1}:2888:3888;${NODE_2}:2888:3888;${NODE_3}:2888:3888"  # add

      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_PEER_PORT: 2888
      ZOOKEEPER_LEADER_PORT: 3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: "true"
    volumes:
      - "data-zk-log:/var/lib/zookeeper/log"
      - "data-zk-data:/var/lib/zookeeper/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - kafka_net


  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - "./data/kafka:/var/lib/kafka/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      KAFKA_BROKER_ID: 1                                                                # change
      KAFKA_ZOOKEEPER_CONNECT: "${NODE_1}:12181,${NODE_2}:22181,${NODE_3}:32181"        # add, change, corresponds to: zookeeper->ports->?2181:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${NODE_1}:9092                            # change
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - kafka_net


volumes:
  data-zk-log:
  data-zk-data:

networks:
  kafka_net:
    name: kafka_network
